# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 192.168.137.1
nameserver fec0:0:0:ffff::1
nameserver fec0:0:0:ffff::2
search mshome.net
~
~