code --install-extension aaron-bond.better-comments
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.path-intellisense
code --install-extension cweijan.vscode-mysql-client2
code --install-extension cweijan.vscode-office
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension ericsonj.verilogformat
code --install-extension formulahendry.auto-rename-tag
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension haskell.haskell
code --install-extension justusadam.language-haskell
code --install-extension LeetCode.vscode-leetcode
code --install-extension matklad.rust-analyzer
code --install-extension mikestead.dotenv
code --install-extension MS-CEINTL.vscode-language-pack-zh-hans
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension mshr-h.veriloghdl
code --install-extension NicholasHsiang.vscode-vue2-snippets
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension PolyMeilex.wgsl
code --install-extension redhat.fabric8-analytics
code --install-extension redhat.vscode-commons
code --install-extension rust-lang.rust
code --install-extension sdras.vue-vscode-snippets
code --install-extension serayuzgur.crates
code --install-extension shardulm94.trailing-spaces
code --install-extension Swellaby.rust-pack
code --install-extension sysoev.language-stylus
code --install-extension vadimcn.vscode-lldb
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-spring-initializr
code --install-extension xabikos.JavaScriptSnippets
