[package]
name = "my-redis"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "", feature = "full" }
mini-redis = ""

# bytes类型相当于 Arc<Vec<u8>>
bytes = ""
