

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library1
    username: root
    password: hj689753
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
server:
  port: 8080

mybatis-plus:
  # 打印sql语句
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # @EnumValue配置
  type-enums-package: com.southwind.mybatis_plus.enums
  # @TableLogic
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1