[package]
name = "hello_macro_derive"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
mroc-macro = true
# 声明hello-macro是一个过程宏

[dependencies]
syn = "1.0"
quote = "1.0"
