/* Generated by Yosys 0.10+16 (git sha1 d8f6d7b1, clang 12.0.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "counter.v:1.1-12.10" *)
module counter(clk, rst, en, count);
  (* force_downto = 32'd1 *)
  (* src = "counter.v:10.19-10.31|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _00_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:10.19-10.31|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _01_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:10.19-10.31|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _02_;
  (* src = "counter.v:3.10-3.13" *)
  input clk;
  (* src = "counter.v:4.21-4.26" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "counter.v:3.20-3.22" *)
  input en;
  (* src = "counter.v:3.15-3.18" *)
  input rst;
  (* src = "counter.v:6.4-10.32" *)
  always @(posedge clk)
    if (rst) count[0] <= 1'h0;
    else if (en) count[0] <= _01_[0];
  (* src = "counter.v:6.4-10.32" *)
  always @(posedge clk)
    if (rst) count[1] <= 1'h0;
    else if (en) count[1] <= _02_[1];
  (* src = "counter.v:6.4-10.32" *)
  always @(posedge clk)
    if (rst) count[2] <= 1'h0;
    else if (en) count[2] <= _02_[2];
  (* src = "counter.v:6.4-10.32" *)
  always @(posedge clk)
    if (rst) count[3] <= 1'h0;
    else if (en) count[3] <= _02_[3];
  assign _01_[0] = ~count[0];
  assign _00_[1] = count[1] &(* src = "counter.v:10.19-10.31|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  count[0];
  assign _00_[2] = count[2] &(* src = "counter.v:10.19-10.31|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[1];
  assign _02_[1] = count[1] ^(* src = "counter.v:10.19-10.31|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  count[0];
  assign _02_[2] = count[2] ^(* src = "counter.v:10.19-10.31|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[1];
  assign _02_[3] = count[3] ^(* src = "counter.v:10.19-10.31|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_[2];
  assign _00_[0] = count[0];
  assign _01_[3:1] = count[3:1];
  assign _02_[0] = _01_[0];
endmodule
